# This file was generated by Phoenix's wscript.

VERSION_STRING    = '4.0.0a1'
MAJOR_VERSION     = 4
MINOR_VERSION     = 0
RELEASE_NUMBER    = 0

VERSION = (MAJOR_VERSION, MINOR_VERSION, RELEASE_NUMBER, 'a1')
